<div style="width: 100%; clear: both;">
    <div style="float: left; width: 50%;">
        <img src="../figs/uoc_masterbrand_3linies_positiu.png", align="left">
    </div>
    <div style="float: right; width: 50%;">
        <p style="margin: 0; padding-top: 22px; text-align:right;">M2.855 · Modelos avanzados de minería de datos</p>
        <p style="margin: 0; text-align:right;">Máster universitario en Ciencia de datos (<i>Data science</i>)</p>
        <p style="margin: 0; text-align:right; padding-button: 100px;">Estudios de Informática, Multimedia y Telecomunicación</p>
    </div>
</div>
<div style="width:100%;">&nbsp;</div>

# Ejemplo de clasificación mediante SVM

## 1. Carga de los datos

En primer lugar, cargaremos el conjunto de datos IRIS dataset (Más información en https://archive.ics.uci.edu/ml/datasets/iris). Este se puede descargar de Internet o puede cargarse directamente de la librería `scikit-learn`, que incorpora un conjunto de datasets muy conocidos y empleados para minería de datos y machine learning.

In [1]:
from sklearn import datasets

# import some data to play with
iris = datasets.load_iris()
X = iris.data
y = iris.target
class_names = iris.target_names

## 2. Preparación del conjunto de entrenamiento y test

Generamos los conjuntos de entrenamiento y test mediante la librería `train_test_split`.

In [2]:
from sklearn.model_selection import train_test_split

# Split the data into a training set and a test set
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

## 3. Creación y entrenamiento del modelo

Las siguientes líneas de código crean y entrenan un modelo basado en SVM.

In [3]:
from sklearn import svm

# Run classifier
classifier = svm.SVC(kernel='linear', C=0.1)
classifier.fit(X_train, y_train)

SVC(C=0.1, kernel='linear')

## 4. Validación del modelo

En primer lugar, comprovaremos la precisión sobre el conjunto de datos de test. Y, seguidamente, crearemos la matriz de confusión asociada.

In [4]:
from sklearn.metrics import confusion_matrix
import numpy as np

# Prediction on test data
y_pred = classifier.predict(X_test)

# Compute confusion matrix
cnf_matrix = confusion_matrix(y_test, y_pred)
np.set_printoptions(precision=2)

print(cnf_matrix)

[[13  0  0]
 [ 0 15  1]
 [ 0  0  9]]
